export const Login = "login"
export const ForgotPassword = "verifyEmail"
export const UpdatePassword = "updatePassword"
export const ChangePassword = "changePassword"
export const FetchCategoryRoute = "category/viewCategory";
export const UpdateCategoryRoute = "category/updateCategory";
export const AddCategoryRoute = "category/addCategory";
export const DeleteCategoryRoute = "category/deleteCategory";
export const FileUploadRoute="fileupload";
export const ListCategoryRoute="category/listofcategories";
export const FetchProductRoute = "products/get";
export const AddProductRoute = "products/addproduct";
export const FetchProductRoutes = "products/viewproduct";       
export const UpdateProductRoute = "products/editproduct";       
export const ListProductRoute = "products/listofProducts";   
export const DeleteProductRoute = "products/deleteproduct";      
export const ProductFileUploadRoute = "products/upload";
export const OrderReportRoute="order/orders-report";
export const UserReportRoute="order/users-report";
export const DashboardStatistic="dashboard/dashboard-statistic"
export const DashboardPurchaseOrder="dashboard/dashboard-purchase-order"