export const Login = "login"
export const ForgotPassword = "verifyEmail"
export const UpdatePassword = "updatePassword"
export const ChangePassword = "changePassword"
export const FetchCategoryRoute = "category/viewCategory";
export const UpdateCategoryRoute = "category/updateCategory";
export const AddCategoryRoute = "category/addCategory";
export const DeleteCategoryRoute = "category/deleteCategory";
export const FileUpload="fileupload";
export const ListCategoryRoute="category/listofcategories";